### PR TITLE
Remove Cephei dependency/add rootless support

### PR DESCRIPTION
**Pull request by singlekeycap**
Hi Anthony, this PR is solely to remove the Cephei dependency, as it has not been updated for rootless yet. Changing preferences works just fine and they apply with no issue (on iOS 13-14). I couldn't get it to work on my device, as it crashes on iOS 15 rootless.

EDIT: Sorry for editing the makefiles so much, my setup didn't allow me to compile them as they were before. You're welcome to change them back.

### CODE REVIEW

**Comment by atar13** [comment]
Hey Andrea. I really appreciate that you put this PR together. I don't have an iOS 15 rootless device, so without these changes Vaon would probably not have been updated to iOS 15 for a while. The changes make sense and shouldn't break functionality but I'm going to do a sanity check on my iOS 14 device. It may take me a few days since I need to get my Theos dev environment up and again, but once I've verified everything looks good I'll merge this and push the release to repos.

**Comment by singlekeycap** [comment]
No worries, take your time. Regarding the iOS 15 crash I'll investigate what the cause is and if I ever figure it out I'll PR a fix for it (if I find it). Thank you for making the tweak open source.

**Comment by atar13** [comment]
If you have any crash logs, I'd be glad to check them out. I used to use [Cr4shed](https://github.com/Muirey03/Cr4shed) to see them (not sure if it's still compatible on iOS 15 rootless)

**Comment by singlekeycap** [comment]
Unfortunately it doesn't, though there are alternatives which I have installed. It's fairly late at night and I do have to be up for work in the morning so I'll get the logs tomorrow if you don't mind.

**Comment by singlekeycap** [comment]
[Here](https://www.dropbox.com/s/7nyvfsvvrj66vu2/SpringBoard_Crash_Log.txt?dl=0) is the SpringBoard crash log that I pulled from [KrashKop](https://havoc.app/package/krashkop). I wasn't able to get a syslog as there's too much garbage in between.

EDIT: Here are logs that match Vaon (otherwise there's too much garbage). There's not much info but I hope they can be useful
```May 19 11:41:37 cfprefsd(rootlesshooks.dylib)[99585] <Notice>: Plist redirected to /var/jb: /var/mobile/Library/Preferences/com.atar13.vaonprefs.plist
May 19 11:41:37 cfprefsd(rootlesshooks.dylib)[99585] <Notice>: Plist redirected to /var/jb: /var/mobile/Library/Preferences/com.atar13.vaonprefs.plist
May 19 11:41:37 cfprefsd(rootlesshooks.dylib)[99585] <Notice>: Plist redirected to /var/jb: /var/mobile/Library/Preferences/com.atar13.vaonprefs.plist
May 19 11:41:37 cfprefsd(rootlesshooks.dylib)[99585] <Notice>: Plist redirected to /var/jb: /private/var/preferences/com.atar13.vaonprefs.plist
May 19 11:41:37 cfprefsd(rootlesshooks.dylib)[99585] <Notice>: Plist redirected to /var/jb: /private/var/preferences/com.atar13.vaonprefs.plist
May 19 11:41:37 cfprefsd(rootlesshooks.dylib)[99585] <Notice>: Plist redirected to /var/jb: /private/var/preferences/com.atar13.vaonprefs.plist
May 19 11:41:38 SpringBoard(Vaon.dylib)[7470] <Notice>: Vaon updateScrollWidthAndTouchPassthrough 0.000000
May 19 11:41:38 SpringBoard(Vaon.dylib)[7470] <Notice>: Vaon updateScrollWidthAndTouchPassthrough 400.000000
May 19 11:41:38 SpringBoard(Vaon.dylib)[7470] <Notice>: Vaon updateScrollWidthAndTouchPassthrough 0
May 19 11:41:38 SpringBoard(Vaon.dylib)[7470] <Notice>: Vaon updateScrollWidthAndTouchPassthrough 0.000000
May 19 11:41:38 SpringBoard(Vaon.dylib)[7470] <Notice>: Vaon updateScrollWidthAndTouchPassthrough 400.000000
May 19 11:41:38 SpringBoard(Vaon.dylib)[7470] <Notice>: Vaon updateScrollWidthAndTouchPassthrough 0

**Comment by atar13** [comment]
According to the backtrace, it seems that the initBatteryView function is causing the crash https://github.com/atar13/Vaon/blob/master/Vaon.xm#L579-L650. I'm not sure what exactly inside the function is causing the crash but I'd assume some of the iOS headers may have changed in iOS 15. If I had to guess, maybe something dealing with Bluetooth devices https://github.com/atar13/Vaon/blob/master/Vaon.xm#L602. When I get the chance, I can take a deeper look at iOS 15 headers to see if anything has changed.

**Comment by singlekeycap** [comment]
Ok so as you might have noticed, I am a complete noob when it comes to Obj-C development and iOS tweak development in general. I attempted to use [this project](https://github.com/leptos-null/Batsie) to see if what you mentioned was the cause, and the app crashes as soon as it attempts to pull battery info, with - from what I can tell - the same error as Vaon.

EDIT: I did add a file check for rootless jailbreaks so the respring button works on them btw. I don't believe it breaks rootful but I haven't had the chance to check.
EDIT 2: Checked with a buddy who has the iOS 14 rootful device I tested my original changes on, the respring button still functions (on both architectures now).

**Comment by atar13** [comment]
Really appreciate the testing with that other BatteryCenter tweak. That narrows it down a ton. I'll do some digging in the headers to see how the framework has changed in iOS 15.

**Comment by singlekeycap** [comment]
Looking through the headers for BCBatteryDeviceController between iOS 14 and iOS 15, it seems iOS 15 is missing these two lines:
```
+(id)sharedInstance;
-(void)connectedDevicesWithResult:(/*^block*/id)arg1 ;
```
Looking through what you're doing with the controller, `sharedInstance` is used when unavailable. From what I read it might be possible to create a wrapper for BCBatteryDeviceController to emulate what `sharedInstance` did, but I'm not sure how to integrate that.

EDIT: In BCBatteryDevice, iOS 15 changes `BOOL batterySaverModeActive` to `BOOL lowPowerModeActive`, which comes with an added value, `-(BOOL)isBatterySaverModeActive;`. Additionally, there are these changes (left being iOS 14, right being iOS 15):
```
-(void)setBatterySaverModeActive:(BOOL)arg1 ;   -->   -(void)setLowPowerModeActive:(BOOL)arg1 ;
-(BOOL)isBatterySaverModeActive;   -->   -(BOOL)isLowPowerModeActive;
```
The rest is all the same. There is one instance of isBatterySaverModeActive [here](https://github.com/atar13/Vaon/blob/master/Vaon.xm#L395), but it seems that it should still work as the original isBatterySaverModeActive value seems to still exist (unsure whether or not it still works).

**Comment by singlekeycap** [comment]
Hi Anthony, I got the tweak to work on rootless and updated the makefiles to build for both platforms. I haven't had the opportunity to test functionality on rootful, but now it doesn't crash on rootless and has functioning battery info+glyphs. Thank you for the pointer to the cause of the crash. I know this is a bit of an ask, but would it be possible to add me in the credits for the next version as I've made the necessary fixes? Thanks.

EDIT: As expected, it seems isBatterySaverModeActive still works.
EDIT 2: I just realized the change breaks iOS 13 support. An easy fix to that would be to add the ios14 vs ios13 check for the devices list to use the correct method. Otherwise, iOS 13 support could be dropped as the tweak hasn't had a need for updates since a year or two ago, making the tweak slimmer and with fewer checks.
EDIT 3: After testing with my buddy on iOS 14, the tweak no longer functions. I'll update the code with a patch for that issue tomorrow.
EDIT 4: Turns out there are more issues with iOS 15. If both the iOS 13 and iOS 14 battery update functions aren't called, the tweak works fine. Otherwise, it breaks.

**Comment by singlekeycap** [comment]
Ok, I'm unsure what went wrong but I think the iOS version check happens after the initial loading of the battery info, which causes the tweak not to load. Updating battery info does not work yet as a new `iOS15UpdateBattery` function needs to be written to work with iOS 15 apparently (using the iOS 14 one doesn't seem to work).

EDIT: Disregard, I got it to work with a sketchy workaround (which still works on rootful). Committing now

**Comment by atar13** [comment]
> 

Yeah absolutely I can add you to the credits. You've contributed quite a bit and basically revived this tweak for iOS 15. I saw you added them to the settings and control files. I think those are the main spots but I can also add you to the tweak's depiction when the update is pushed.

**Comment by atar13** [comment]
> Ok, I'm unsure what went wrong but I think the iOS version check happens after the initial loading of the battery info, which causes the tweak not to load. Updating battery info does not work yet as a new `iOS15UpdateBattery` function needs to be written to work with iOS 15 apparently (using the iOS 14 one doesn't seem to work).
> 
> EDIT: Disregard, I got it to work with a sketchy workaround (which still works on rootful). Committing now

I'm not quite sure why it wasn't working before the workaround but its fine as is.  As I understand it, it's working now on iOS 15 and iOS 14 (based on the feedback from your iOS 14 friend).

I've been a bit bogged down with school the past few days, but I got my Theos dev environment setup and I'll give it a test on my iOS 14 device later today. Once that's done, I think we should be good to merge and publish.

**Comment by singlekeycap** [comment]
I totally understand, take your time. iOS 13 support is also unfazed as I didn't touch that part. I made a mistake prior to the workaround which was causing the `iOS14UpdateBattery` function to not run, which was why battery info was not being displayed. Thank you for approving the credits as well, I know some devs would rather slap their name on it and call it a day.

**Review by atar13 — APPROVED** [review]
Just tested it and it seems like iOS 14 is working fine. Saving/loading preferences and the core functionality work just like before. 

Once again, thanks for the contribution and all the iOS 15 debugging.

**Pull request merged**
